2013-01-15 14:09:15.621000: ENGINE starting
2013-01-15 14:09:15.622000: ENGINE loading STUDENT ENGINE part 2
2013-01-15 14:09:15.632000: ENGINE loaded player module: OKComputer as player 1
2013-01-15 14:09:15.632000: QUORIDOR ENGINE CLIENT 1.0.5 by Adam Oest initializing
2013-01-15 14:09:16.134000: ENGINE calling STUDENT ENGINE init
2013-01-15 14:09:16.134000: STUDENT ENGINE init call successfully returned
2013-01-15 14:09:16.134000: ENGINE calling init() for player 1
2013-01-15 14:09:16.135000: OKComputer initialized as player 1
2013-01-15 14:09:16.156000: ENGINE GUI accessible at:
https://adelaide.cs.rit.edu/~royale/quoridorui/gameview/gameid.42093/partone.0/apikey.36bc8c65d1d4af66485/public.19522551b8210f842039d9153b0e2c2db2ceca6650f5a959a66d2/animations.500/
2013-01-15 14:09:16.157000: ENGINE processing move # 1
2013-01-15 14:09:16.157000: ENGINE getting move for player 1 from PRE_MOVE list 
2013-01-15 14:09:16.157000: ENGINE validating player 1 move. Player 1 Move: [8,4] -> [7,4]
2013-01-15 14:09:16.157000: ENGINE calling STUDENT ENGINE validate_move
2013-01-15 14:09:20.727000: STUDENT ENGINE validate_move call successfully returned
2013-01-15 14:09:20.727000: ENGINE uploading move to web engine
2013-01-15 14:09:20.877000: ENGINE detects correct move validation by STUDENT ENGINE
2013-01-15 14:09:20.877000: ENGINE calling STUDENT ENGINE last_move
2013-01-15 14:09:20.877000: ERROR: 'Board' object is not subscriptable
2013-01-15 14:09:20.878000: TRACE: 
Traceback (most recent call last):
  File "C:\Users\Adam\Desktop\a\Quoridor_Client_2121\Releases\1.0.5\Python3.2\Model\__init__.py", line 560, in studentEngineCall
  File "C:\Users\Joe\Documents\GitHub\Quoridor\StudentEngines\jak3122\__init__.py", line 89, in last_move
    the_board[source_coord].pawnId = 0                     # remove pawn from source square
TypeError: 'Board' object is not subscriptable

2013-01-15 14:09:20.878000: ERROR: 2013-01-15 14:09:20.878000: ENGINE exiting due to STUDENT ENGINE exception

2013-01-15 14:09:20.879000: TRACE: 
Traceback (most recent call last):
  File "C:\Users\Adam\Desktop\a\Quoridor_Client_2121\Releases\1.0.5\Python3.2\Engine\controller.py", line 270, in nextTurn
  File "C:\Users\Adam\Desktop\a\Quoridor_Client_2121\Releases\1.0.5\Python3.2\Model\__init__.py", line 567, in studentEngineCall
Engine.security.GameException: 2013-01-15 14:09:20.878000: ENGINE exiting due to STUDENT ENGINE exception


2013-01-15 14:09:21.015000: 2013-01-15 14:09:20.878000: ENGINE exiting due to STUDENT ENGINE exception

2013-01-15 14:09:21.016000: ENGINE finished with next move
2013-01-15 14:09:21.016000: ENGINE shutting down
